export const CardList = [
    {
        name:"Invoker",
        image:"/heroes/invoker.jpg",
        isFlipped:false,
    },
    {
        name:"Kunkka",
        image:"/heroes/kunkka.jpg",
        isFlipped:false,
    },
    {
        name:"Rubick",
        image:"/heroes/rubick.jpg",
        isFlipped:false,
    },
    {
        name:"Clinkz",
        image:"/heroes/clinkz.jpg",
        isFlipped:false,
    },
    {
        name:"Wind Ranger",
        image:"/heroes/windranger.jpg",
        isFlipped:false,
    },
    {
        name:"Undying",
        image:"/heroes/undying.jpg",
        isFlipped:false,
    },
    {
        name:"Storm Spirit",
        image:"/heroes/storm-spirit.jpg",
        isFlipped:false,
    },
    {
        name:"Juggernaut",
        image:"/heroes/juggernaut.jpg",
        isFlipped:false,
    },
    {
        name:"Invoker",
        image:"/heroes/invoker.jpg",
        isFlipped:false,
    },
    {
        name:"Kunkka",
        image:"/heroes/kunkka.jpg",
        isFlipped:false,
    },
    {
        name:"Rubick",
        image:"/heroes/rubick.jpg",
        isFlipped:false,
    },
    {
        name:"Clinkz",
        image:"/heroes/clinkz.jpg",
        isFlipped:false,
    },
    {
        name:"Wind Ranger",
        image:"/heroes/windranger.jpg",
        isFlipped:false,
    },
    {
        name:"Undying",
        image:"/heroes/undying.jpg",
        isFlipped:false,
    },
    {
        name:"Storm Spirit",
        image:"/heroes/storm-spirit.jpg",
        isFlipped:false,
    },
    {
        name:"Juggernaut",
        image:"/heroes/juggernaut.jpg",
        isFlipped:false,
    },
]